export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  HR_MANAGER = 'HR_MANAGER',
  DEPT_HEAD = 'DEPT_HEAD',
  TEAM_LEAD = 'TEAM_LEAD',
  EMPLOYEE = 'EMPLOYEE',
}

export enum OfficeLocation {
  BD = 'BD',
  UK = 'UK',
}

export enum Currency {
  BDT = 'BDT',
  GBP = 'GBP',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERN = 'INTERN',
}

export enum EmploymentStatus {
  ACTIVE = 'ACTIVE',
  PROBATION = 'PROBATION',
  NOTICE_PERIOD = 'NOTICE_PERIOD',
  TERMINATED = 'TERMINATED',
  ON_LEAVE = 'ON_LEAVE',
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  EARLY_DEPARTURE = 'EARLY_DEPARTURE',
  HALF_DAY = 'HALF_DAY',
  ON_LEAVE = 'ON_LEAVE',
  HOLIDAY = 'HOLIDAY',
  WEEKEND = 'WEEKEND',
}

export enum AttendanceSource {
  BIOMETRIC = 'BIOMETRIC',
  RFID = 'RFID',
  MANUAL = 'MANUAL',
  SELF = 'SELF',
  SYSTEM = 'SYSTEM',
}

export enum TimesheetStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum PayrollStatus {
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  APPROVED = 'APPROVED',
  PAID = 'PAID',
}

export enum DocumentType {
  OFFER_LETTER = 'OFFER_LETTER',
  NDA = 'NDA',
  CONTRACT = 'CONTRACT',
  ID_PROOF = 'ID_PROOF',
  PAYSLIP = 'PAYSLIP',
  CERTIFICATE = 'CERTIFICATE',
  OTHER = 'OTHER',
}

export enum NotificationType {
  LEAVE_REQUESTED = 'LEAVE_REQUESTED',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',
  LEAVE_CANCELLED = 'LEAVE_CANCELLED',
  TIMESHEET_SUBMITTED = 'TIMESHEET_SUBMITTED',
  TIMESHEET_APPROVED = 'TIMESHEET_APPROVED',
  TIMESHEET_REJECTED = 'TIMESHEET_REJECTED',
  PAYSLIP_READY = 'PAYSLIP_READY',
  ATTENDANCE_FLAGGED = 'ATTENDANCE_FLAGGED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  ONBOARDING_TASK = 'ONBOARDING_TASK',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  PERFORMANCE_REVIEW = 'PERFORMANCE_REVIEW',
}

export enum OnboardingTaskCategory {
  DOCUMENT = 'DOCUMENT',
  IT_SETUP = 'IT_SETUP',
  TRAINING = 'TRAINING',
  COMPLIANCE = 'COMPLIANCE',
  ASSET = 'ASSET',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
}

export enum TaxRegime {
  BD_INCOME_TAX = 'BD_INCOME_TAX',
  UK_PAYE = 'UK_PAYE',
}
